import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { CloukitStoryModule } from '../index';
import { DemoComponent } from './demo.component';
import { Story00Component } from './stories/story-00';
import { CloukitStoryService } from '../components/story.service';
import demoStoriesSource from './demo-stories-source.json';


@NgModule({
  declarations: [ DemoComponent, Story00Component ],
  exports: [ DemoComponent ],
  imports: [
    CommonModule,
    CloukitStoryModule,
  ],
  providers: [ ],
  bootstrap: [ ],
})
export class DemoModule {
  constructor(private cloukitStoryService: CloukitStoryService) {
    //
    // INITIALIZE STORY SOURCES
    //
    const baseUrl = document.getElementsByTagName('base')[0].href;
    const storySourceJsonUrl = `${baseUrl}assets/demoStoriesSource.json`; // File is auto generated by build chain!
    this.cloukitStoryService.loadStoryJson(storySourceJsonUrl);
  }
}
